// Mock data for testing without Supabase
export const mockDesigners = [
  {
    id: '1',
    name: 'Sabyasachi Mukherjee',
    bio: 'India\'s master of luxury bridal couture',
    commission_percentage: 12,
  },
  {
    id: '2',
    name: 'Manish Malhotra',
    bio: 'Iconic bridal and celebrity wear designer',
    commission_percentage: 15,
  },
  {
    id: '3',
    name: 'Tarun Tahiliani',
    bio: 'Pioneer of contemporary Indian fashion',
    commission_percentage: 10,
  },
  {
    id: '4',
    name: 'Anita Dongre',
    bio: 'Sustainable luxury Indian fashion',
    commission_percentage: 12,
  },
  {
    id: '5',
    name: 'Payal Singhal',
    bio: 'Contemporary luxury Indian designer',
    commission_percentage: 11,
  },
]

export const mockProducts = [
  {
    id: '1',
    name: 'Embroidered Bridal Lehenga',
    designer: 'Sabyasachi Mukherjee',
    designer_id: '1',
    price: 3500,
    mrp: 5000,
    sku: 'SAB001',
    category: 'Lehenga',
    description: 'Exquisite hand-embroidered bridal lehenga with intricate zardozi work',
    fabric: '100% Pure Silk',
    embroidery: 'Hand-embroidered zardozi and pearl work',
    care_instructions: 'Dry clean only',
    delivery_days: 7,
    image: '/images/products/product1.jpg',
  },
  {
    id: '2',
    name: 'Luxury Silk Saree',
    designer: 'Manish Malhotra',
    designer_id: '2',
    price: 2200,
    mrp: 3500,
    sku: 'MAN001',
    category: 'Saree',
    description: 'Premium silk saree with traditional weaving',
    fabric: 'Mulberry Silk',
    embroidery: 'Traditional hand work',
    care_instructions: 'Dry clean recommended',
    delivery_days: 5,
    image: '/images/products/product2.jpg',
  },
  {
    id: '3',
    name: 'Designer Anarkali Suit',
    designer: 'Tarun Tahiliani',
    designer_id: '3',
    price: 1800,
    mrp: 2800,
    sku: 'TAR001',
    category: 'Suit',
    description: 'Contemporary Anarkali with detailed embroidery',
    fabric: 'Georgette',
    embroidery: 'Resham and beadwork',
    care_instructions: 'Gentle wash',
    delivery_days: 5,
    image: '/images/products/product3.jpg',
  },
  {
    id: '4',
    name: 'Wedding Sharara',
    designer: 'Anita Dongre',
    designer_id: '4',
    price: 2800,
    mrp: 4200,
    sku: 'AND001',
    category: 'Sharara',
    description: 'Elegant sharara perfect for weddings',
    fabric: 'Chiffon blend',
    embroidery: 'Gold thread embroidery',
    care_instructions: 'Dry clean only',
    delivery_days: 7,
    image: '/images/products/product4.jpg',
  },
  {
    id: '5',
    name: 'Luxury Pret Suit',
    designer: 'Payal Singhal',
    designer_id: '5',
    price: 1500,
    mrp: 2200,
    sku: 'PAY001',
    category: 'Pret',
    description: 'Ready-to-wear luxury pret suit',
    fabric: 'Cotton silk',
    embroidery: 'Minimal embroidery',
    care_instructions: 'Machine wash cold',
    delivery_days: 3,
    image: '/images/products/product1.jpg',
  },
]

export const mockOrders = [
  {
    id: '1',
    orderNumber: 'SC234001',
    customer: 'Priya Sharma',
    amount: 3500,
    status: 'Delivered',
    date: new Date('2024-01-15'),
    items: 1,
  },
  {
    id: '2',
    orderNumber: 'SC234002',
    customer: 'Anjali Patel',
    amount: 2200,
    status: 'Shipped',
    date: new Date('2024-01-10'),
    items: 1,
  },
]

export const mockAppointments = [
  {
    id: '1',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+1 (555) 123-4567',
    occasion: 'Wedding',
    date: new Date('2024-02-15'),
    time: '2:00 PM',
    status: 'Confirmed',
  },
  {
    id: '2',
    name: 'Meera Kapoor',
    email: 'meera@example.com',
    phone: '+1 (555) 234-5678',
    occasion: 'Engagement',
    date: new Date('2024-02-20'),
    time: '10:00 AM',
    status: 'Pending',
  },
]
